"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Shell } from "@/components/Shell";
import { apiFetch, subjects } from "@/lib/api";
type StudyLog = { id: string; subject: string; study_minutes: number; studied_at: string; memo?: string };
type StudyList = { items: StudyLog[]; total: number; page: number; page_size: number };
export default function StudyPage() {
  const [data, setData] = useState<StudyList | null>(null); const [page, setPage] = useState(1); const [subject, setSubject] = useState(""); const [studiedAt, setStudiedAt] = useState(""); const [toast, setToast] = useState("");
  async function load() { const params = new URLSearchParams({ page: String(page) }); if (subject) params.set("subject", subject); if (studiedAt) params.set("studied_at", studiedAt); setData(await apiFetch<StudyList>(`/study?${params}`)); }
  useEffect(() => { load().catch((e) => setToast(e.message)); }, [page, subject, studiedAt]);
  async function remove(id: string) { if (!confirm("本当に削除しますか？")) return; await apiFetch(`/study/${id}`, { method: "DELETE" }); setToast("削除しました"); load(); }
  const pages = data ? Math.max(1, Math.ceil(data.total / data.page_size)) : 1;
  return <Shell><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">学習記録</h1><p className="text-slate-600">新しい順に20件ずつ表示します</p></div><Link className="btn-primary" href="/study/new">追加</Link></div>{toast && <p className="mb-4 rounded-md bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{toast}</p>}<section className="panel mb-5 grid gap-3 md:grid-cols-3"><select className="field" value={subject} onChange={(e) => { setPage(1); setSubject(e.target.value); }}><option value="">すべての教科</option>{subjects.map((s) => <option key={s}>{s}</option>)}</select><input className="field" type="date" value={studiedAt} onChange={(e) => { setPage(1); setStudiedAt(e.target.value); }} /><button className="btn-secondary" onClick={() => { setSubject(""); setStudiedAt(""); }}>検索をクリア</button></section><section className="panel overflow-x-auto">{!data ? <p>読み込み中...</p> : <table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">教科</th><th>学習時間</th><th>学習日</th><th>メモ</th><th></th></tr></thead><tbody>{data.items.map((log) => <tr className="border-b last:border-0" key={log.id}><td className="py-3 font-semibold">{log.subject}</td><td>{log.study_minutes}分</td><td>{log.studied_at}</td><td className="max-w-xs truncate">{log.memo}</td><td className="space-x-2 text-right"><Link className="font-semibold text-focus" href={`/study/edit/${log.id}`}>編集</Link><button className="font-semibold text-coral" onClick={() => remove(log.id)}>削除</button></td></tr>)}</tbody></table>}{data?.items.length === 0 && <p className="py-4 text-slate-500">記録がありません</p>}</section><div className="mt-4 flex items-center justify-end gap-2"><button className="btn-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>前へ</button><span className="text-sm font-semibold">{page} / {pages}</span><button className="btn-secondary" disabled={page >= pages} onClick={() => setPage(page + 1)}>次へ</button></div></Shell>;
}
