"use client";
import { useEffect, useState } from "react";
import { Shell } from "@/components/Shell";
import { apiFetch } from "@/lib/api";
type Dashboard = { today_minutes: number; week_minutes: number; month_minutes: number; subject_shares: { subject: string; minutes: number; percent: number }[]; recent_logs: { id: string; subject: string; study_minutes: number; studied_at: string }[] };
export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiFetch<Dashboard>("/dashboard").then(setData).catch((e) => setError(e.message)); }, []);
  return <Shell><div className="mb-6"><h1 className="text-3xl font-bold">ダッシュボード</h1><p className="text-slate-600">学習状況をひと目で確認できます</p></div>{error && <p className="panel text-red-700">{error}</p>}{!data ? <p className="panel">読み込み中...</p> : <div className="grid gap-5"><section className="grid gap-4 md:grid-cols-3"><Stat title="今日" value={data.today_minutes} /><Stat title="今週" value={data.week_minutes} /><Stat title="今月" value={data.month_minutes} /></section><section className="grid gap-5 lg:grid-cols-2"><div className="panel"><h2 className="mb-4 text-lg font-bold">教科別割合</h2><div className="grid gap-3">{data.subject_shares.length === 0 && <p className="text-slate-500">まだ記録がありません</p>}{data.subject_shares.map((s) => <div key={s.subject}><div className="mb-1 flex justify-between text-sm font-semibold"><span>{s.subject}</span><span>{s.percent}%</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-mint" style={{ width: `${s.percent}%` }} /></div></div>)}</div></div><div className="panel"><h2 className="mb-4 text-lg font-bold">最近の学習</h2><div className="grid gap-3">{data.recent_logs.length === 0 && <p className="text-slate-500">最新5件がここに表示されます</p>}{data.recent_logs.map((log) => <div className="rounded-md border border-slate-200 p-3" key={log.id}><div className="flex justify-between font-semibold"><span>{log.subject}</span><span>{log.study_minutes}分</span></div><p className="text-sm text-slate-600">{log.studied_at}</p></div>)}</div></div></section></div>}</Shell>;
}
function Stat({ title, value }: { title: string; value: number }) { return <div className="panel"><p className="text-sm font-semibold text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}<span className="ml-1 text-base text-slate-500">分</span></p></div>; }
